variables:
  solution: 'cs/FASTER.sln'
  RunAzureTests: 'no'

jobs:
- job: 'csharpWindows'  
  pool:
    vmImage: vs2017-win2016    
  displayName: 'C# (Windows)'

  strategy:
    maxParallel: 2
    matrix:
      AnyCPU-Debug:
        buildPlatform: 'Any CPU'
        buildConfiguration: 'Debug'
      AnyCPU-Release:
        buildPlatform: 'Any CPU'
        buildConfiguration: 'Release'
      x64-Debug:
        buildPlatform: 'x64'
        buildConfiguration: 'Debug'
      x64-Release:
        buildPlatform: 'x64'
        buildConfiguration: 'Release'
  
  steps:
  - task: NuGetToolInstaller@0
    inputs:
      versionSpec: '4.8.2' 
    
  - task: NuGetCommand@2
    inputs:
      restoreSolution: '$(solution)'

  - task: VSBuild@1
    inputs:
      solution: '$(solution)'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

  - task: VSTest@2
    inputs:
      testAssemblyVer2: |
       **\$(BuildConfiguration)\net46*\*test*.dll
       **\$(BuildConfiguration)\**\net46*\*test*.dll
       !**\*Microsoft.VisualStudio.TestPlatform*
       !**\obj\**
       !**\*TestAdapter.dll
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'
      otherConsoleOptions: '/Framework:.NETFramework,Version=v4.0 /Tests:"SessionTest,SimpleRecoveryTest"'

  - task: VSTest@2
    inputs:
      testAssemblyVer2: |
       **\$(BuildConfiguration)\netcoreapp*\*test*.dll
       **\$(BuildConfiguration)\**\netcoreapp*\*test*.dll
       !**\*Microsoft.VisualStudio.TestPlatform*
       !**\obj\**
       !**\*TestAdapter.dll
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'
      otherConsoleOptions: '/Framework:.NETCoreApp,Version=v2.0 /Tests:"SimpleRecoveryTest"'
